---
- import_playbook: ../common-packer/provision/baseline.yaml
- hosts: all
  become_user: root
  become_method: sudo

  tasks:
    - name: "Install pre-requisites"
      yum:
        name: 
          - gcc
          - g++
          - make
        state: present
    - name: "Add nodejs repo"
      shell: curl --silent --location https://rpm.nodesource.com/setup_14.x | sudo bash -
    - name: "Install nodejs"
      yum:
        name: nodejs
        state: present
